CREATE TABLE A(ID INTEGER PRIMARY KEY, A TEXT, N CHAR(1), G CHAR(1), C INTEGER);
CREATE TABLE A_P(A_P TEXT);
CREATE TABLE B(ID INTEGER PRIMARY KEY, B_S TEXT, B_P TEXT);
CREATE TABLE C_A(C_A_S_M TEXT, C_A_S_F TEXT, C_A_P_M TEXT, C_A_P_F TEXT);
CREATE TABLE C_M(C_M_S TEXT, C_M_P TEXT);

INSERT INTO A(ID, A, N, G, C) VALUES(0, 'A vida ', 'S', 'F', 0);
INSERT INTO A(A, N, G, C) VALUES('O amor ', 'S', 'M', 0);
INSERT INTO A(A, N, G, C) VALUES('A nossa existência ', 'S', 'F', 0);
INSERT INTO A(A, N, G, C) VALUES('Os amigos ', 'P', 'M', 0);
INSERT INTO A(A, N, G, C) VALUES('A mente ', 'S', 'F', 0);
INSERT INTO A(A, N, G, C) VALUES('A nossa caminhada pela vida ', 'S', 'F', 0);
INSERT INTO A(A, N, G, C) VALUES('As cicatrizes que ganhamos ao longo da vida ', 'P', 'F', 0);
INSERT INTO A(A, N, G, C) VALUES('A seta do cupido ', 'S', 'F', 0);
INSERT INTO A(A, N, G, C) VALUES('A montanha ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('As escadas ', 'P', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('A caminhada ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('A corrida ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('A escadaria ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('O labirinto ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('A espiral ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('A rotunda ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('O mar ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('A luz ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('A aura ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('A jornada ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('A viagem ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('O ritmo ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('A pegada ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('O recheio ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('O carrossel ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('O comboio ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('A cicatriz ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('O poço ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('A jangada ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('O milagre ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('As linhas ', 'P', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('A encruzilhada ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('O hino ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('Os valores ', 'P', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('O fenómeno ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('A caverna ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('O túnel ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('A montanha-russa ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('A nossa história ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('O esquema do avião ', 'S', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('A dicotomia ', 'S', 'F', 1);
INSERT INTO A(A, N, G, C) VALUES('Os pilares ', 'P', 'M', 1);
INSERT INTO A(A, N, G, C) VALUES('O caminho ', 'S', 'M', 1);

INSERT INTO A_P(A_P) VALUES('do sucesso ');
INSERT INTO A_P(A_P) VALUES('da vida ');
INSERT INTO A_P(A_P) VALUES('do amor ');
INSERT INTO A_P(A_P) VALUES('da realização pessoal ');
INSERT INTO A_P(A_P) VALUES('da coragem ');
INSERT INTO A_P(A_P) VALUES('da sabedoria ');
INSERT INTO A_P(A_P) VALUES('da paz ');
INSERT INTO A_P(A_P) VALUES('da paz interior ');
INSERT INTO A_P(A_P) VALUES('da revolta ');
INSERT INTO A_P(A_P) VALUES('do caos ');
INSERT INTO A_P(A_P) VALUES('da liberdade ');
INSERT INTO A_P(A_P) VALUES('da inocência ');
INSERT INTO A_P(A_P) VALUES('da justiça ');
INSERT INTO A_P(A_P) VALUES('dos valores ');
INSERT INTO A_P(A_P) VALUES('do respeito ');
INSERT INTO A_P(A_P) VALUES('do carisma ');
INSERT INTO A_P(A_P) VALUES('do futuro ');
INSERT INTO A_P(A_P) VALUES('da infância ');
INSERT INTO A_P(A_P) VALUES('do saber ');
INSERT INTO A_P(A_P) VALUES('da felicidade ');

INSERT INTO B(B_S, B_P) VALUES('faz sentido', 'fazem sentido');
INSERT INTO B(B_S, B_P) VALUES('não espera por ninguém', 'não esperam por ninguém');
INSERT INTO B(B_S, B_P) VALUES('deixa os mais fracos para trás', 'deixam os mais fracos para trás');
INSERT INTO B(B_S, B_P) VALUES('supera todas as barreiras', 'superam todas as barreiras');
INSERT INTO B(B_S, B_P) VALUES('move montanhas', 'movem montanhas');
INSERT INTO B(B_S, B_P) VALUES('chama por nós', 'chamam por nós');
INSERT INTO B(B_S, B_P) VALUES('está sempre à espreita', 'estão sempre à espreita');
INSERT INTO B(B_S, B_P) VALUES('tem muitas surpresas', 'têm muitas surpresas');
INSERT INTO B(B_S, B_P) VALUES('tem altos e baixos', 'têm altos e baixos');
INSERT INTO B(B_S, B_P) VALUES('faz parte da nossa historia', 'fazem parte da nossa história');
INSERT INTO B(B_S, B_P) VALUES('não é o que parece', 'não são o que parecem');
INSERT INTO B(B_S, B_P) VALUES('às vezes engana-nos', 'às vezes enganam-nos');

INSERT INTO C_A(C_A_S_M, C_A_S_F, C_A_P_M, C_A_P_F) VALUES('importante', 'importante', 'importantes', 'importantes');
INSERT INTO C_A(C_A_S_M, C_A_S_F, C_A_P_M, C_A_P_F) VALUES('determinante', 'determinante', 'determinantes', 'determinantes');
INSERT INTO C_A(C_A_S_M, C_A_S_F, C_A_P_M, C_A_P_F) VALUES('a vida', 'a vida', 'a vida', 'a vida');
INSERT INTO C_A(C_A_S_M, C_A_S_F, C_A_P_M, C_A_P_F) VALUES('tóxico', 'tóxica', 'tóxicos', 'tóxicas');

INSERT INTO C_M(C_M_S, C_M_P) VALUES('um pastel de nata', 'pastéis de nata');
INSERT INTO C_M(C_M_S, C_M_P) VALUES('farófias', 'farófias');
INSERT INTO C_M(C_M_S, C_M_P) VALUES('bolo de chocolate', 'bolo de chocolate');
INSERT INTO C_M(C_M_S, C_M_P) VALUES('um mar revolto', 'um mar revolto');
INSERT INTO C_M(C_M_S, C_M_P) VALUES('um oásis no deserto', 'oásis no deserto');
INSERT INTO C_M(C_M_S, C_M_P) VALUES('o caminho de um rio até ao mar', 'o caminho de um rio até ao mar');
INSERT INTO C_M(C_M_S, C_M_P) VALUES('uma escada rolante', 'escadas rolantes');
INSERT INTO C_M(C_M_S, C_M_P) VALUES('uma bola de berlim', 'uma bola de berlim');
INSERT INTO C_M(C_M_S, C_M_P) VALUES('uma cascata congelada', 'uma cascata congelada');
INSERT INTO C_M(C_M_S, C_M_P) VALUES('um relâmpago', 'relâmpagos');
INSERT INTO C_M(C_M_S, C_M_P) VALUES('escalar o Evereste', 'escalar o Evereste');
